# fly.toml file generated for blue-night-9371 on 2021-03-12T16:40:01+03:30

app = "blue-night-9371"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
private_network = true

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "30s" # seems to take about 30s to boot
    interval = "10s"
    port = "8080"
    restart_limit = 0
    timeout = "2s"